# Generated by Django 5.0.1 on 2024-03-28 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='username',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', message='Le numéro de téléphone doit contenir uniquement des chiffres.')]),
        ),
    ]
