# Generated by Django 5.0.3 on 2024-04-24 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_utilisateur_theme_sombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='lu',
            new_name='vu',
        ),
    ]
