# Generated by Django 4.2.13 on 2024-06-11 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='autoriser_empreinte',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='en_train_decrire',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='theme_sombre',
        ),
    ]
