# Generated by Django 5.0.1 on 2024-03-28 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0004_alter_utilisateur_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('envoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envoi', to=settings.AUTH_USER_MODEL)),
                ('recoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
