# Generated by Django 5.0.3 on 2024-04-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0004_utilisateur_en_train_decrire'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='autoriser_empreinte',
            field=models.BooleanField(default=False),
        ),
    ]
