# Generated by Django 5.0.3 on 2024-04-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0006_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
    ]
