# Generated by Django 5.0.3 on 2024-04-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0007_remove_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='messages/images/'),
        ),
    ]
